---
Greenhouse:
  SimulationSpace:
    # Dimensions of the simulation space. The largest dimension should be exactly 1.
    no_voxel_x: 1
    no_voxel_y: 1
    no_voxel_z: 1
    oxygen_sample_geometry_path: ./vessel_graph_generation/geometries/ATM_253/ATM_253_{}.npy
#    oxygen_sample_geometry_path: ./vessel_graph_generation/geometries/ATM_255/ATM_255_{}.npy
#    oxygen_sample_geometry_path: ./vessel_graph_generation/geometries/ATM_257/ATM_257_{}.npy
  d: 0.05 #0.1
  r: 0.0035 #0.0025
  FAZ_radius_bound: # The FAZ radius is randomly drawn from a normal distribution with these parameters
    - 0.01 #0.44
    - 0.005 #0.04
  rotation_radius: 1.05 # The radius from the FAZ center in which to apply the rotation term
  FAZ_center: # x-y position of the FAZ
    - 0.5
    - 0.5
  param_scale: 3 # Parameter scale used to scale all spatial parameters. 3 means we generate a 3 mm x 3 mm image.
  modes: # List of sequential growth stages. We first develop the superficial vascular complex (SVC), then the deep vascular complex (DVC)
    - name: trachea
      I: 10 # Number of iterations
      N: 1000 # Number of added oxygen sinks (OSs) per iteration
      eps_n: 0.18 # Minimal distance between nodes and OSs [mm]
      eps_s: 0.135 # Min. distance between OSs [mm]
      eps_k: 0.135 # Satisfaction range of nodes [mm]
      delta_art: 0.5 #0.2925 # Distance of perception volume for arterial nodes [mm]
      delta_ven: 0.2925 # Distance of perception volume for venous nodes [mm]
      gamma_art: 50 # Angle of perception cone w.r.t. parent for arterial nodes [°]
      gamma_ven: 50 # Angle of perception cone w.r.t. parent for venous nodes [°]
      phi: 15 # Minimal std of attraction vector angles for symetric bifurcation
      omega: 0.05 # 0.3 # Weighting factor optimal growth direction
      kappa: 2.55 # Bifurcation exponent
      delta_sigma: 0 #0.02 # Linear growth rate of simulation space per iter
    - name: 1_bronchi
      I: 20
      N: 2000
      eps_n: 0.09
      eps_s: 0.0675
      eps_k: 0.0675
      delta_art: 0.1
      delta_ven: 0.14625
      gamma_art: 90
      gamma_ven: 90
      phi: 15
      omega: 0
      kappa: 2.9
      delta_sigma: 0
output:
  directory: ./vessel_graph_generation/datasets/lobes # Output directory
  image_scale_factor: 512 # Number of pixels for the largest image dimension. Final dimensions are calculated based on simulation space dimensions.
  save_trees: true # If true, save the generated vessel graph as a csv file
  save_3D_volumes: nifti # "null": Do not save 3D volume, "npy": Save as numpy array, "nifti": Save as NIFTI file
  save_2D_image: true # If true, save the pixelized Maximum intensity projection along the proj_axis
  proj_axis: 2 # Axis alogn which to calculate the MIP for 2D image generation
  save_stats: true # Save statistics about growth process
Forest:
  type: bronchi # Initialize forest by tree stumps at the faces of the 3D volume
  source_walls: # Faces along wich to place the initial tree stumps
    x0: true
    x1: false
    y0: false
    y1: false
    z0: false
    z1: false
  N_trees: 1 # Number of separate trees that are grown simultanously
  nerve_center: [0.43,0.88] # If type is set to nerve, this is the x-y position of the nerve
  nerve_radius: [0.01] # Radius of the optical nerve
  segment_root_path: ./vessel_graph_generation/geometries/ATM_253/ATM_253_roots.yml
#  segment_root_path: ./vessel_graph_generation/geometries/ATM_255/ATM_255_roots.yml
#  segment_root_path: ./vessel_graph_generation/geometries/ATM_257/ATM_257_roots.yml
mode: 'airways'
