---
Greenhouse:
  SimulationSpace:
    geometry_path: None
  d: 0.05
  r: 0.0023
  param_scale: 3 # Parameter scale used to scale all spatial parameters. 3 means we generate a 3 mm x 3 mm image.
  modes: # List of sequential growth stages. We first develop the superficial vascular complex (SVC), then the deep vascular complex (DVC)
    - name: main_vessels
      I: 10 # Number of iterations
      N: 2000 # Number of added oxygen sinks (OSs) per iteration
      eps_n: 0.18 # Minimal distance between nodes and OSs [mm]
      eps_s: 0.135 # Min. distance between OSs [mm]
      eps_k: 0.135 # Satisfaction range of nodes [mm]
      delta_art: 0.2 #0.2925 # Distance of perception volume for arterial nodes [mm]
      delta_ven: 0.2925 # Distance of perception volume for venous nodes [mm]
      gamma_art: 60 # Angle of perception cone w.r.t. parent for arterial nodes [°]
      gamma_ven: 50 # Angle of perception cone w.r.t. parent for venous nodes [°]
      phi: 15 # Minimal std of attraction vector angles for symetric bifurcation
      omega: 0.05 # 0.3 # Weighting factor optimal growth direction
      kappa: 2.55 # Bifurcation exponent
      delta_sigma: 0.2 #0.02 # Linear growth rate of simulation space per iter
    - name: smaller_vessels
      I: 100
      N: 2000
      eps_n: 0.055
      eps_s: 0.035
      eps_k: 0.035
      delta_art: 0.1
      delta_ven: 0.14625
      gamma_art: 90
      gamma_ven: 90
      phi: 0
      omega: 0
      kappa: 2.9
      delta_sigma: 0
output:
  directory: /home/ahaas/data/1_simulated_data #./vessel_graph_generation/datasets/7_base_scans # Output directory
  image_scale_factor: 512 # Number of pixels for the largest image dimension. Final dimensions are calculated based on simulation space dimensions.
  save_trees: true # If true, save the generated vessel graph as a csv file
  save_3D_volumes: null  # "null": Do not save 3D volume, "npy": Save as numpy array, "nifti": Save as NIFTI file
  save_2D_image: true # If true, save the pixelized Maximum intensity projection along the proj_axis
  proj_axis: 2 # Axis alogn which to calculate the MIP for 2D image generation
  save_stats: true # Save statistics about growth process
Forest:
  type: bronchi # Initialize forest by tree stumps at the faces of the 3D volume
  
geometry_path: /home/ahaas/data/0_input_simulation/geometries
ATM_path: /home/shared/Data/ATM22/train/images
mode: vessels
ATM_scans: ['010', '027', '056', '057', '116', '175', '221', '253', '255', '257']
